/*
  # Add Sample Games with Multiple Genres

  1. Sample Games
    - Add games with various genres to showcase multi-genre support
    - Include different platforms and pricing strategies
    - Realistic game data with proper categorization

  2. Genre Variety
    - Action, Adventure, RPG, Strategy, Simulation, Sports, Racing
    - Puzzle, Horror, Platformer, Fighting, Shooter, Battle Royale
    - MMORPG, Indie, Arcade, Casual genres
*/

-- Clear existing sample data first
DELETE FROM games;

-- Insert diverse games across multiple genres
INSERT INTO games (title, description, price, discount_percentage, discount_amount, is_free, genre, image_url, platforms, about_game, developer, publisher, release_date, minimum_specs) VALUES
  (
    'Cyber Nexus 2077',
    'A futuristic cyberpunk adventure where you navigate through neon-lit cities and uncover corporate conspiracies. Features stunning visuals and immersive gameplay.',
    299000,
    25,
    NULL,
    false,
    'Action',
    'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg',
    ARRAY['PC', 'PS5'],
    'Experience the ultimate cyberpunk adventure in a world where technology and humanity collide. Navigate through sprawling megacities, hack into corporate networks, and uncover a conspiracy that threatens the very fabric of society.',
    'Neon Studios',
    'KGR Games',
    '2024-01-15',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-8400 / AMD Ryzen 5 2600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1060 6GB / AMD RX 580 8GB", "directx": "Version 12", "storage": "50 GB available space"}'::jsonb
  ),
  (
    'Mystic Realms Online',
    'Embark on an epic fantasy MMORPG journey through magical kingdoms. Cast spells, battle mythical creatures, and forge your destiny.',
    199000,
    NULL,
    NULL,
    false,
    'MMORPG',
    'https://images.pexels.com/photos/1174732/pexels-photo-1174732.jpeg',
    ARRAY['PC', 'PS4', 'PS5'],
    'Join millions of players in the most immersive fantasy MMORPG ever created. Choose from 12 unique classes, explore vast continents, and participate in epic guild wars.',
    'Fantasy Works',
    'KGR Games',
    '2023-11-20',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i3-8100 / AMD Ryzen 3 2200G", "memory": "6 GB RAM", "graphics": "NVIDIA GTX 1050 Ti / AMD RX 570", "directx": "Version 11", "storage": "35 GB available space"}'::jsonb
  ),
  (
    'Speed Legends Championship',
    'High-octane racing game featuring exotic cars and challenging tracks around the world. Customize your vehicles and compete in championship races.',
    179000,
    NULL,
    30000,
    false,
    'Racing',
    'https://images.pexels.com/photos/544966/pexels-photo-544966.jpeg',
    ARRAY['PC', 'PS5'],
    'Feel the adrenaline rush of professional racing with the most realistic driving physics ever created. Race through iconic locations worldwide.',
    'Speed Dynamics',
    'Racing Pro',
    '2024-03-10',
    '{"os": "Windows 11 64-bit", "processor": "Intel Core i5-10400 / AMD Ryzen 5 3600", "memory": "12 GB RAM", "graphics": "NVIDIA RTX 3060 / AMD RX 6600 XT", "directx": "Version 12", "storage": "75 GB available space"}'::jsonb
  ),
  (
    'Brain Teaser Collection',
    'Challenge your mind with hundreds of brain-teasing puzzles. Perfect for casual gaming sessions with progressively difficult levels.',
    0,
    NULL,
    NULL,
    true,
    'Puzzle',
    'https://images.pexels.com/photos/1040157/pexels-photo-1040157.jpeg',
    ARRAY['PC'],
    'Exercise your brain with over 500 unique puzzles designed by cognitive scientists. Features adaptive difficulty and progress tracking.',
    'Mind Games Studio',
    'KGR Games',
    '2024-02-01',
    NULL
  ),
  (
    'Galactic Empire Builder',
    'Build and manage your space empire in this deep strategy simulation. Explore galaxies, manage resources, and engage in diplomatic warfare.',
    249000,
    15,
    NULL,
    false,
    'Strategy',
    'https://images.pexels.com/photos/586063/pexels-photo-586063.jpeg',
    ARRAY['PC'],
    'Command vast fleets, colonize planets, and shape the destiny of entire civilizations in this grand strategy masterpiece.',
    'Stellar Strategy',
    'KGR Games',
    '2024-01-30',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-9400 / AMD Ryzen 5 3600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1660 / AMD RX 5500 XT", "directx": "Version 11", "storage": "40 GB available space"}'::jsonb
  ),
  (
    'Retro Fighter Arena',
    'Classic 2D fighting game with modern mechanics. Choose from 20 unique fighters and master devastating combo attacks.',
    89000,
    NULL,
    NULL,
    false,
    'Fighting',
    'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg',
    ARRAY['PC', 'PS4', 'PS5'],
    'Experience the golden age of fighting games with hand-drawn sprites, fluid animations, and competitive online multiplayer.',
    'Arcade Legends',
    'Fighting Pro',
    '2024-02-14',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i3-8100 / AMD Ryzen 3 2200G", "memory": "4 GB RAM", "graphics": "NVIDIA GTX 1050 / AMD RX 560", "directx": "Version 11", "storage": "15 GB available space"}'::jsonb
  ),
  (
    'Horror Mansion: Nightmare',
    'Survive the night in this spine-chilling horror adventure. Solve puzzles, avoid terrifying creatures, and uncover dark secrets.',
    129000,
    NULL,
    20000,
    false,
    'Horror',
    'https://images.pexels.com/photos/1174732/pexels-photo-1174732.jpeg',
    ARRAY['PC', 'PS5'],
    'Enter a world of psychological horror where every shadow hides a threat. Use your wits to survive until dawn.',
    'Nightmare Studios',
    'Horror Games Inc',
    '2024-10-31',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-8400 / AMD Ryzen 5 2600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1060 / AMD RX 580", "directx": "Version 12", "storage": "25 GB available space"}'::jsonb
  ),
  (
    'Pixel Adventure Quest',
    'A charming 2D platformer with hand-drawn art and memorable characters. Jump, run, and explore beautifully crafted levels.',
    0,
    NULL,
    NULL,
    true,
    'Platformer',
    'https://images.pexels.com/photos/544966/pexels-photo-544966.jpeg',
    ARRAY['PC'],
    'Embark on a whimsical journey through magical worlds filled with secrets, collectibles, and challenging platforming sequences.',
    'Pixel Art Games',
    'Indie Collective',
    '2024-01-10',
    NULL
  ),
  (
    'Battle Royale Legends',
    'Drop into intense multiplayer battles with up to 100 players. Scavenge for weapons, build fortifications, and be the last one standing.',
    0,
    NULL,
    NULL,
    true,
    'Battle Royale',
    'https://images.pexels.com/photos/1040157/pexels-photo-1040157.jpeg',
    ARRAY['PC', 'PS4', 'PS5'],
    'The ultimate battle royale experience with destructible environments, unique character abilities, and constantly evolving gameplay.',
    'Battle Studios',
    'KGR Games',
    '2023-12-15',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-8400 / AMD Ryzen 5 2600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1060 / AMD RX 580", "directx": "Version 12", "storage": "30 GB available space"}'::jsonb
  ),
  (
    'City Builder Deluxe',
    'Design and manage your dream city. Balance resources, keep citizens happy, and create a thriving metropolis.',
    199000,
    20,
    NULL,
    false,
    'Simulation',
    'https://images.pexels.com/photos/586063/pexels-photo-586063.jpeg',
    ARRAY['PC'],
    'Build the city of your dreams with advanced simulation mechanics, realistic traffic systems, and dynamic weather effects.',
    'Urban Planners',
    'Simulation Games',
    '2024-02-20',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-9400 / AMD Ryzen 5 3600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1660 / AMD RX 5500 XT", "directx": "Version 11", "storage": "45 GB available space"}'::jsonb
  ),
  (
    'Medieval Conquest Wars',
    'Lead your kingdom to glory in this medieval strategy game. Build castles, train armies, and conquer neighboring lands.',
    159000,
    NULL,
    NULL,
    false,
    'Strategy',
    'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg',
    ARRAY['PC', 'PS4'],
    'Command medieval armies in epic real-time battles. Manage your kingdom, forge alliances, and expand your empire across Europe.',
    'Medieval Studios',
    'Strategy Masters',
    '2024-03-01',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-8400 / AMD Ryzen 5 2600", "memory": "6 GB RAM", "graphics": "NVIDIA GTX 1050 Ti / AMD RX 570", "directx": "Version 11", "storage": "35 GB available space"}'::jsonb
  ),
  (
    'Space Shooter Elite',
    'Fast-paced space combat with stunning visuals. Pilot advanced starfighters and engage in epic space battles.',
    99000,
    30,
    NULL,
    false,
    'Shooter',
    'https://images.pexels.com/photos/1174732/pexels-photo-1174732.jpeg',
    ARRAY['PC', 'PS5'],
    'Experience intense space combat with cutting-edge graphics and responsive controls. Features both single-player campaign and multiplayer modes.',
    'Space Combat Inc',
    'Shooter Games',
    '2024-01-25',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-8400 / AMD Ryzen 5 2600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1060 / AMD RX 580", "directx": "Version 12", "storage": "20 GB available space"}'::jsonb
  ),
  (
    'Football Manager 2024',
    'Manage your favorite football team to glory. Handle transfers, tactics, and lead your team to championship victory.',
    219000,
    NULL,
    NULL,
    false,
    'Sports',
    'https://images.pexels.com/photos/544966/pexels-photo-544966.jpeg',
    ARRAY['PC', 'PS4', 'PS5'],
    'The most realistic football management simulation ever created. Features over 2,500 clubs from around the world.',
    'Sports Interactive',
    'Football Games Ltd',
    '2024-02-28',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i5-8400 / AMD Ryzen 5 2600", "memory": "8 GB RAM", "graphics": "NVIDIA GTX 1050 / AMD RX 560", "directx": "Version 11", "storage": "30 GB available space"}'::jsonb
  ),
  (
    'Indie Art Adventure',
    'A unique artistic journey through surreal landscapes. Solve creative puzzles and experience a story told through visual art.',
    79000,
    NULL,
    NULL,
    false,
    'Indie',
    'https://images.pexels.com/photos/1040157/pexels-photo-1040157.jpeg',
    ARRAY['PC'],
    'An emotional journey through hand-painted worlds that blur the line between game and art. Winner of multiple indie game awards.',
    'Artistic Vision',
    'Indie Collective',
    '2024-01-05',
    '{"os": "Windows 10 64-bit", "processor": "Intel Core i3-8100 / AMD Ryzen 3 2200G", "memory": "4 GB RAM", "graphics": "NVIDIA GTX 1050 / AMD RX 560", "directx": "Version 11", "storage": "10 GB available space"}'::jsonb
  ),
  (
    'Casual Garden Paradise',
    'Relax and unwind while building your perfect garden. Plant flowers, attract butterflies, and create a peaceful sanctuary.',
    0,
    NULL,
    NULL,
    true,
    'Casual',
    'https://images.pexels.com/photos/586063/pexels-photo-586063.jpeg',
    ARRAY['PC'],
    'A peaceful gaming experience perfect for relaxation. No time pressure, no competition - just pure zen gardening.',
    'Zen Games',
    'Casual Studios',
    '2024-02-10',
    NULL
  ),
  (
    'Retro Arcade Classics',
    'A nostalgic collection of classic arcade games reimagined for modern platforms. Includes 50+ games with updated graphics.',
    0,
    NULL,
    NULL,
    true,
    'Arcade',
    'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg',
    ARRAY['PC'],
    'Relive the golden age of arcade gaming with this comprehensive collection of timeless classics, all updated for modern systems.',
    'Retro Games',
    'Arcade Collection',
    '2024-01-20',
    NULL
  );